# -----------------------------------------
# 데이터베이스 (Mysql, Redis)
#------------------------------------------

spring:
  config:
    activate:
      on-profile: local-glog-redis-docker
    redis:
      object:
        host: localhost
        port: 6379
        use-cluster: N
        cluster:
          nodes: loc1:6379,loc2:6379
      sessionObject:
        host: localhost
        port: 6379
        use-cluster: N
        cluster:
          nodes: loc1:6379,loc2:6379
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session:LSUBS
    store-type: redis
